---
version: latest

codebattle:
  replicaCount: 1
  image:
    repository: codebattle/codebattle
    imagePullPolicy: Always

runner:
  replicaCount: 2
  image:
    repository: codebattle/runner
    imagePullPolicy: Always

chatbot:
  replicaCount: 1
  image:
    repository: codebattle/chat_bot
    imagePullPolicy: Always
    tag: "0.0.1"

nginx:
  image:
    repository: codebattle/nginx
    imagePullPolicy: Always

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
