apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codebattle-ingress
spec:
  tls:
    - hosts:
      - ya-codebattle.xyz
      secretName: k8s-secret
  ingressClassName: nginx
  rules:
    - host: ya-codebattle.xyz
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: codebattle
                port:
                  number: 80
