name: Build PR

on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    # Use test environment by default
    env:
      MIX_ENV: test

    services:
      db:
        image: postgres:16-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name=pg_ci
          --mount type=tmpfs,destination=/var/lib/postgresql/data

    steps:
      - uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.2"
          elixir-version: "1.18.2"

      - name: Restore mix build cache
        uses: actions/cache@v4
        with:
          path: ./services/app/deps
          key: ${{ runner.os }}-deps-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-deps-

      - name: Restore Build Cache
        uses: actions/cache@v4
        with:
          path: ./services/app/_build
          key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-build-

      - name: Get deps
        run: mix deps.get
        working-directory: ./services/app

      - name: Mix deps.compile
        run: mix compile --warnings-as-errors
        working-directory: ./services/app

      - name: Mix format
        run: mix format --check-formatted
        working-directory: ./services/app

      - name: Mix credo
        run: mix credo
        working-directory: ./services/app

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install yarn dependencies
        run: yarn install --froze-lockfile
        working-directory: ./services/app/apps/codebattle

      - name: Eslint
        run: yarn lint
        working-directory: ./services/app/apps/codebattle

      - name: Run jest
        run: yarn test
        working-directory: ./services/app/apps/codebattle

      - name: Setup db
        run: mix ecto.create && mix ecto.migrate
        working-directory: ./services/app

      - name: Mix tests
        run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./services/app/assp/codebattle/cover/excoveralls.json
          fail_ci_if_error: false
